### ISSUE TITLE
issue when sampling from a trained prior

### ISSUE THREAD

**Issue by wenchangzhou-qtx** [MorganCThomas/SMILES-RNN#18]
Hey @MorganCThomas,

Thanks for putting putting such a nice repo which I find potentially would be very very useful for me, I used the trained chembl data prior provided in this repo, and tried this one but failed, pls see below the issue:

I tried this just to decorate a toluene, `python scripts/sample_model.py -p priors/ChEMBL28pur.ckpt -m RNN -o test.smi -n 100 --unique --psmiles 'C(*)c1ccccc1'`

The issue I got is:
```
Device set to cpu
Traceback (most recent call last):
  File "/home/softwares/SMILES-RNN/scripts/sample_model.py", line 158, in <module>
    main(args)
  File "/home/softwares/SMILES-RNN/scripts/sample_model.py", line 57, in main
    smiles, _ = model.sample_smiles(
  File "/home/softwares/mambaforge3/envs/molscore/lib/python3.9/site-packages/smilesrnn/rnn.py", line 476, in sample_smiles
    self._batch_sample_decorate(
  File "/home/softwares/mambaforge3/envs/molscore/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/softwares/mambaforge3/envs/molscore/lib/python3.9/site-packages/smilesrnn/rnn.py", line 828, in _batch_sample_decorate
    raise DeprecationWarning
DeprecationWarning
```

Can you point out where I should be checking to make it work? Thanks!

**Comment by MorganCThomas** [comment]
Hi @wenchangzhou-qtx,

My apologies, I had deprecated the old version but had not switched to the new standalone implementation of PromptSMILES yet. I've just pushed a hotfix b86a5b7 which should now implement it, albeit without the `--unique` flag for now. I've tested it on your command it for me it works fine. 

**Some recommendations**:
1. As in the [paper](https://chemrxiv.org/engage/chemrxiv/article-details/65e718eee9ebbb4db9f21886), one caveat is you might find low values of uniqueness with this approach. You can either,
- Run RL with MolScore and simply reward molecules for being unique to enrich this which works very well.
- Try sampling with a higher temperature (which will be a trade-off with validity)
2. I am not actively developing this repo anymore, I've switched to [this one](https://github.com/Acellera/acegen-open), check it out if you're interested!

If you need any help, have any issues, or have any feature requests (either here or in the other repo) then let me know.

**Comment by wenchangzhou-qtx** [comment]
Thanks! @MorganCThomas I know acegen and I like it a lot, will start from there, seems docking mode is also possible from molscore, super NICE!
