### ISSUE TITLE
Error while running reinforcement.py script

### ISSUE THREAD

**Issue by surendramph** [MorganCThomas/SMILES-RNN#4]
Hi,

Running the reinforcement_learning.py code, the following error occurred.

(molscore) medicina@medicina:SMILES-RNN$ python reinforcement_learning.py -p Prior_GuacaMol_reprod_lstm_Epoch-10.ckpt -m ret_sim_config.json --model RNN RV2
Found existing directory, appending current time to distinguish
Device set to cuda
  0%|                                                                                                                         | 0/250 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/media/medicina/SMILES-RNN/model/RL.py", line 84, in _score
    scores = self.scoring_function(smiles)
  File "/media/medicina/SMILES-RNN/molscore/manager.py", line 586, in __call__
    self.run_scoring_functions(smiles=smiles_to_process, file_names=file_names)
  File "/media/medicina/SMILES-RNN/molscore/manager.py", line 248, in run_scoring_functions
    results = function(smiles=smiles, directory=self.save_dir, file_names=file_names)
  File "/media/medicina/SMILES-RNN/molscore/scoring_functions/similarity.py", line 102, in __call__
    with Pool(self.n_jobs) as pool:
  File "/home/medicina/anaconda3/envs/molscore/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/medicina/anaconda3/envs/molscore/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/home/medicina/anaconda3/envs/molscore/lib/python3.6/multiprocessing/pool.py", line 229, in _repopulate_pool
    for i in range(self._processes - len(self._pool)):
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reinforcement_learning.py", line 157, in <module>
    main(args)
  File "reinforcement_learning.py", line 49, in main
    record = RL.train(n_steps=args.n_steps, save_freq=args.save_freq)
  File "/media/medicina/SMILES-RNN/model/RL.py", line 50, in train
    self._train_step(step=step)
  File "/media/medicina/SMILES-RNN/model/RL.py", line 187, in _train_step
    scores = self._score(smiles, step)
  File "/media/medicina/SMILES-RNN/model/RL.py", line 93, in _score
    self.scoring_function.write_scores()
  File "/media/medicina/SMILES-RNN/molscore/manager.py", line 415, in write_scores
    temp = self.main_df.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

What kind of error is this? Please help.

Thanks

**Comment by MorganCThomas** [comment]
Hi, could you please also share the contents of your ret_sim_config.json? This way I can try to reproduce the error

**Comment by surendramph** [comment]
> Hi, could you please also share the contents of your ret_sim_config.json? This way I can try to reproduce the error

here is the config file.

[ret_sim_config.zip](https://github.com/MorganCThomas/SMILES-RNN/files/9784509/ret_sim_config.zip)

**Comment by MorganCThomas** [comment]
Thank you, this is actually an error with MolScore (https://github.com/MorganCThomas/MolScore)

The error is because you're passing a float to the n_jobs parameter. I.e change 1.0 -> 1

It is now running with the **develop** branch (https://github.com/MorganCThomas/MolScore/tree/develop) and I recommend writing configs by using `streamlit run molscore/gui/config_generator.py` as this will ensure all parameters are the correct format. 

FYI please also specify a prefix so that you don't get unexpected results if running multiple scoring functions.

**Comment by surendramph** [comment]
Thank you so much for checking the error. Now It is working fine.
